// Generated by CoffeeScript 1.3.3
(function() {

  requirejs(['parser', 'scanner', 'input_reader', 'scanner_words_analyser', 'time_patterns_analyser'], function(Parser, Scanner, InputReader, ScannerWordsAnalyser, TimePatternsAnalyser) {
    window.todo = {};
    return window.todo.time = function(inputValue) {
      var analyseResult, inputReader, parser, result, scanner, scannerWordsAnalyser, timePatternsAnalyser;
      inputReader = new InputReader(inputValue);
      scannerWordsAnalyser = new ScannerWordsAnalyser();
      scanner = new Scanner(inputReader, scannerWordsAnalyser);
      parser = new Parser(scanner);
      result = parser.parse(inputValue);
      timePatternsAnalyser = new TimePatternsAnalyser();
      analyseResult = timePatternsAnalyser.analyse(result);
      return analyseResult;
    };
  });

}).call(this);
