// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var CharChecker;
    return CharChecker = (function() {

      function CharChecker() {}

      CharChecker.numberReg = /^[0-9]$/;

      CharChecker.alphaReg = /^[A-Za-z]$/;

      CharChecker.isNumber = function(char) {
        return this.numberReg.test(char);
      };

      CharChecker.isAlpha = function(char) {
        return this.alphaReg.test(char);
      };

      CharChecker.isColon = function(char) {
        return char === ':';
      };

      return CharChecker;

    })();
  });

}).call(this);
