// Generated by CoffeeScript 1.3.3
(function() {
  var InputReader;

  window.InputReader = InputReader = (function() {

    function InputReader(input) {
      this.input = input;
      this.position = 0;
    }

    InputReader.prototype.nextChar = function() {
      return this.input[this.position++];
    };

    InputReader.prototype.currentChar = function() {
      return this.input[this.position];
    };

    return InputReader;

  })();

}).call(this);
