// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    return $(".parse").click(function() {
      var inputValue, pattersnAnalyser, result;
      inputValue = $(".input").val();
      window.charChecker = new CharChecker();
      window.inputReader = new InputReader(inputValue);
      window.scannerWordsAnalyser = new ScannerWordsAnalyser();
      window.scanner = new Scanner(inputReader, scannerWordsAnalyser);
      window.parser = new Parser(scanner);
      result = parser.parse();
      pattersnAnalyser = new TimePatternsAnalyser();
      return pattersnAnalyser.analyse(result);
    });
  });

}).call(this);
