// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var ScannerWordsanalyser;
    return ScannerWordsanalyser = (function() {

      function ScannerWordsanalyser() {}

      ScannerWordsanalyser.prototype.wordsNumbers = {
        one: 1,
        two: 2,
        three: 3,
        four: 4,
        five: 5,
        six: 6,
        seven: 7,
        eigth: 8,
        nine: 9,
        ten: 10,
        eleven: 11,
        twelve: 12
      };

      ScannerWordsanalyser.prototype.timeModifierCheck = function(token) {
        if (token.raw === 'am' || token.raw === 'pm') {
          return token.token = 'time_modifier';
        }
      };

      ScannerWordsanalyser.prototype.wordNumberCheck = function(token) {
        var number, word, wordsNumbers, _results;
        wordsNumbers = this.wordsNumbers;
        _results = [];
        for (word in wordsNumbers) {
          number = wordsNumbers[word];
          if (word === token.raw) {
            token.token = 'number';
            _results.push(token.value = number);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      return ScannerWordsanalyser;

    })();
  });

}).call(this);
