// Generated by CoffeeScript 1.3.3
(function() {

  define(['patterns/simple', 'patterns/simple_modifier', 'patterns/number', 'patterns/number_modifier'], function(Simple, SimpleModifier, NumberTime, NumberModifierTime) {
    var TimePatternsAnalyser;
    return TimePatternsAnalyser = (function() {

      function TimePatternsAnalyser() {}

      TimePatternsAnalyser.prototype.patterns = [new SimpleModifier(), new Simple(), new NumberModifierTime(), new NumberTime()];

      TimePatternsAnalyser.prototype.analyse = function(tokens) {
        var pattern, result, series, _i, _len, _ref;
        series = _.pluck(tokens, 'token').join(' ');
        result = _.pluck(tokens, 'raw').join(' ');
        _ref = this.patterns;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pattern = _ref[_i];
          if (pattern.check(series) && pattern.validate(tokens)) {
            result = pattern.transform(tokens);
            break;
          }
        }
        return result;
      };

      return TimePatternsAnalyser;

    })();
  });

}).call(this);
