// Generated by CoffeeScript 1.3.3
(function() {

  define(['input_reader', 'char_checker'], function(InputReader, CharChecker) {
    var Token;
    return Token = (function() {

      Token.prototype.raw = '';

      Token.prototype.token = null;

      Token.prototype.value = null;

      function Token(inputReader, token, checker) {
        this.inputReader = inputReader;
        this.token = token;
        this.checker = checker;
        this._readTokenFrom(inputReader);
      }

      Token.prototype._readTokenFrom = function(inputReader) {
        var char;
        if (this.token === 'undef' || this.token === 'colon') {
          this.raw = inputReader.currentChar();
          this.value = this.raw;
          inputReader.nextChar();
          return;
        }
        if (this.token === 'end') {
          return;
        }
        while (this.checker.call(CharChecker, (char = inputReader.currentChar()))) {
          this.raw += char;
          inputReader.nextChar();
        }
        return this.value = this.raw;
      };

      return Token;

    })();
  });

}).call(this);
