// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var NumberTime;
    return NumberTime = (function() {

      function NumberTime() {}

      NumberTime.prototype.sequence = 'number';

      NumberTime.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      NumberTime.prototype.validate = function(tokens) {
        var hoursValid, _ref;
        hoursValid = (0 <= (_ref = tokens[0].value) && _ref <= 23);
        return hoursValid;
      };

      NumberTime.prototype.transform = function(tokens) {
        var hoursValue, minutesValue;
        hoursValue = tokens[0].value;
        hoursValue = hoursValue < 10 ? '0' + hoursValue : hoursValue;
        minutesValue = '00';
        return "" + hoursValue + ":" + minutesValue;
      };

      return NumberTime;

    })();
  });

}).call(this);
