// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var ComplexUnitPattern;
    return ComplexUnitPattern = (function() {

      function ComplexUnitPattern() {}

      ComplexUnitPattern.prototype.sequence = 'number time_unit number time_unit';

      ComplexUnitPattern.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      ComplexUnitPattern.prototype.validate = function(tokens) {
        return true;
      };

      ComplexUnitPattern.prototype.transform = function(tokens) {
        var first, second;
        first = this._calculate(tokens[0].value, tokens[1].value);
        second = this._calculate(tokens[2].value, tokens[3].value);
        return first + second;
      };

      ComplexUnitPattern.prototype._calculate = function(value, unit) {
        var result;
        result = value;
        if (unit === 'h') {
          result *= 60;
        }
        return result;
      };

      return ComplexUnitPattern;

    })();
  });

}).call(this);
