// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var SimplePattern;
    return SimplePattern = (function() {

      function SimplePattern() {}

      SimplePattern.prototype.sequence = 'number';

      SimplePattern.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      SimplePattern.prototype.validate = function(tokens) {
        return true;
      };

      SimplePattern.prototype.transform = function(tokens) {
        return tokens[0].value;
      };

      return SimplePattern;

    })();
  });

}).call(this);
