// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var SimpleUnitPattern;
    return SimpleUnitPattern = (function() {

      function SimpleUnitPattern() {}

      SimpleUnitPattern.prototype.sequence = 'number time_unit';

      SimpleUnitPattern.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      SimpleUnitPattern.prototype.validate = function(tokens) {
        return true;
      };

      SimpleUnitPattern.prototype.transform = function(tokens) {
        var result, time, unit;
        time = tokens[0];
        unit = tokens[1].value;
        result = time.value;
        if (unit === 'h') {
          result *= 60;
        }
        return result;
      };

      return SimpleUnitPattern;

    })();
  });

}).call(this);
