// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var NumberModifierTime;
    return NumberModifierTime = (function() {

      function NumberModifierTime() {}

      NumberModifierTime.prototype.sequence = 'number time_modifier';

      NumberModifierTime.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      NumberModifierTime.prototype.validate = function(tokens) {
        var hoursValid, _ref;
        hoursValid = (0 <= (_ref = tokens[0].value) && _ref <= 23);
        return hoursValid;
      };

      NumberModifierTime.prototype.transform = function(tokens) {
        var hours, hoursValue, minutesValue;
        hours = tokens[0].value;
        if (tokens[1].value === 'pm') {
          hours = tokens[0].value + 12;
        }
        hoursValue = hours;
        hoursValue = hoursValue < 10 ? '0' + hoursValue : hoursValue;
        minutesValue = '00';
        return "" + hoursValue + ":" + minutesValue;
      };

      return NumberModifierTime;

    })();
  });

}).call(this);
