// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var SimpleModifier;
    return SimpleModifier = (function() {

      function SimpleModifier() {}

      SimpleModifier.prototype.sequence = 'number colon number time_modifier';

      SimpleModifier.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      SimpleModifier.prototype.validate = function(tokens) {
        var hoursValid, minutesValid, _ref, _ref1;
        hoursValid = (0 <= (_ref = tokens[0].value) && _ref <= 23);
        minutesValid = (0 <= (_ref1 = tokens[2].value) && _ref1 <= 59);
        return hoursValid && minutesValid;
      };

      SimpleModifier.prototype.transform = function(tokens) {
        var hours, hoursValue, minutesValue;
        hours = tokens[0].value;
        if (tokens[3].value === 'pm') {
          hours = tokens[0].value + 12;
        }
        hoursValue = hours;
        hoursValue = hoursValue < 10 ? '0' + hoursValue : hoursValue;
        minutesValue = tokens[2].value;
        minutesValue = minutesValue < 10 ? '0' + minutesValue : minutesValue;
        return "" + hoursValue + ":" + minutesValue;
      };

      return SimpleModifier;

    })();
  });

}).call(this);
