// Generated by CoffeeScript 1.3.3
(function() {

  define([], function() {
    var SimplePattern;
    return SimplePattern = (function() {

      function SimplePattern() {}

      SimplePattern.prototype.sequence = 'number colon number';

      SimplePattern.prototype.check = function(sequence) {
        return sequence === this.sequence;
      };

      SimplePattern.prototype.validate = function(tokens) {
        var hoursValid, minutesValid, _ref, _ref1;
        hoursValid = (0 <= (_ref = tokens[0].value) && _ref <= 23);
        minutesValid = (0 <= (_ref1 = tokens[2].value) && _ref1 <= 59);
        return hoursValid && minutesValid;
      };

      SimplePattern.prototype.transform = function(tokens) {
        var hoursValue, minutesValue;
        hoursValue = tokens[0].value;
        hoursValue = hoursValue < 10 ? '0' + hoursValue : hoursValue;
        minutesValue = tokens[2].value;
        minutesValue = minutesValue < 10 ? '0' + minutesValue : minutesValue;
        return "" + hoursValue + ":" + minutesValue;
      };

      return SimplePattern;

    })();
  });

}).call(this);
